'use client';

import * as React from 'react';

type Language = 'en' | 'ru' | 'ky';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.projects': 'Projects',
    'nav.tasks': 'My Tasks',
    'nav.teams': 'Teams',
    'nav.calendar': 'Calendar',
    'nav.time': 'Time Tracking',
    'nav.notifications': 'Notifications',
    'nav.settings': 'Settings',
    'nav.analytics': 'Analytics',
    'nav.admin': 'Admin Panel',
    'nav.logout': 'Logout',

    // Admin Navigation
    'nav.admin.title': 'Administration',
    'nav.admin.users': 'Users',
    'nav.admin.projects': 'All Projects',
    'nav.admin.tasks': 'All Tasks',
    'nav.admin.handbooks': 'Handbooks',
    'nav.admin.roles': 'System Roles',
    'nav.admin.permissions': 'Permissions',

    // Admin Page
    'admin.description': 'System administration and management',
    'admin.users.desc': 'Manage user accounts and roles',
    'admin.projects.desc': 'View and manage all projects',
    'admin.tasks.desc': 'View and manage all tasks',
    'admin.handbooks.desc': 'Manage system reference data',
    'admin.roles.desc': 'Manage system roles',
    'admin.permissions.desc': 'Configure API access permissions',

    // Settings page
    'settings.title': 'Settings',
    'settings.description': 'Manage your account settings and preferences',
    'settings.profile': 'Profile',
    'settings.notifications': 'Notifications',
    'settings.appearance': 'Appearance',
    'settings.security': 'Security',
    'settings.profileInfo': 'Profile Information',
    'settings.profileDesc': 'Update your personal information',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phone': 'Phone Number',
    'settings.saveChanges': 'Save Changes',
    'settings.notificationPrefs': 'Notification Preferences',
    'settings.notificationDesc': 'Choose what notifications you want to receive',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotificationsDesc': 'Receive notifications via email',
    'settings.notifyWhen': 'Notify me when:',
    'settings.taskAssigned': 'A task is assigned to me',
    'settings.taskCommented': 'Someone comments on my task',
    'settings.taskCompleted': 'A task I\'m watching is completed',
    'settings.deadlineReminder': 'Task deadline is approaching',
    'settings.appearanceTitle': 'Appearance',
    'settings.appearanceDesc': 'Customize how TaskFlow looks',
    'settings.theme': 'Theme',
    'settings.themeLight': 'Light',
    'settings.themeDark': 'Dark',
    'settings.themeSystem': 'System',
    'settings.themeDesc': 'Select your preferred theme',
    'settings.language': 'Language',
    'settings.languageDesc': 'Choose your preferred language',
    'settings.changePassword': 'Change Password',
    'settings.changePasswordDesc': 'Update your password to keep your account secure',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm New Password',

    // Telegram
    'settings.telegramNotifications': 'Telegram Notifications',
    'settings.telegramNotificationsDesc': 'Receive notifications via Telegram',
    'settings.telegramConnected': 'Connected',
    'settings.telegramNotConnected': 'Not connected',
    'settings.telegramConnect': 'Connect Telegram',
    'settings.telegramDisconnect': 'Disconnect',
    'settings.telegramConnectTitle': 'Connect Telegram',
    'settings.telegramConnectDesc': 'Scan QR code or click the link to connect your Telegram account',
    'settings.telegramCode': 'Your code',
    'settings.telegramOpenBot': 'Open Telegram Bot',
    'settings.telegramConnectedAs': 'Connected as',
    'settings.inAppNotifications': 'In-App Notifications',
    'settings.inAppNotificationsDesc': 'Show notifications in the app',
    'settings.notificationChannels': 'Notification Channels',
    'settings.mentioned': 'Someone mentions me',
    'settings.projectInvite': 'I receive a project invitation',

    // Common
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.create': 'Create',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',

    // Toast messages
    'toast.profileUpdated': 'Profile updated',
    'toast.profileUpdatedDesc': 'Your profile has been successfully updated.',
    'toast.profileError': 'Failed to update profile. Please try again.',
    'toast.passwordChanged': 'Password changed',
    'toast.passwordChangedDesc': 'Your password has been successfully changed.',
    'toast.passwordError': 'Failed to change password. Please check your current password.',

    // Calendar
    'calendar.title': 'Calendar',
    'calendar.description': 'View your tasks and deadlines',
    'calendar.today': 'Today',
    'calendar.selectDate': 'Select a date',
    'calendar.noTasks': 'No tasks due on this date',
    'calendar.clickToView': 'Click on a date to view tasks',
    'calendar.more': 'more',
    'calendar.sun': 'Sun',
    'calendar.mon': 'Mon',
    'calendar.tue': 'Tue',
    'calendar.wed': 'Wed',
    'calendar.thu': 'Thu',
    'calendar.fri': 'Fri',
    'calendar.sat': 'Sat',

    // Tasks
    'tasks.title': 'My Tasks',
    'tasks.description': 'View and manage tasks assigned to you',
    'tasks.search': 'Search tasks...',
    'tasks.filterByStatus': 'Filter by status',
    'tasks.filterAll': 'All Tasks',
    'tasks.filterTodo': 'To Do',
    'tasks.filterInProgress': 'In Progress',
    'tasks.filterDone': 'Done',
    'tasks.filterOverdue': 'Overdue',
    'tasks.noTasks': 'No tasks found',
    'tasks.noTasksDesc': 'Tasks assigned to you will appear here',
    'tasks.tryAdjustingFilters': 'Try adjusting your filters',
    'tasks.today': 'Today',
    'tasks.comments': 'comments',

    // AI Generator
    'nav.admin.aiGenerator': 'AI Generator',
    'admin.aiGenerator.desc': 'Generate forms and tables with AI',
    'ai.generator.title': 'AI Generator',
    'ai.generator.description': 'Generate forms and tables using AI based on natural language descriptions',
    'ai.generator.formTab': 'Form Generator',
    'ai.generator.tableTab': 'Table Generator',
    'ai.generator.formInput': 'Form Description',
    'ai.generator.formInputDesc': 'Describe what kind of form you want to generate',
    'ai.generator.tableInput': 'Table Description',
    'ai.generator.tableInputDesc': 'Describe what kind of table you want to generate',
    'ai.generator.prompt': 'Description',
    'ai.generator.formPromptPlaceholder': 'e.g., Create a user registration form with name, email, password, and phone number fields',
    'ai.generator.tablePromptPlaceholder': 'e.g., Create a table for managing products with name, price, quantity, and category columns',
    'ai.generator.entityType': 'Entity Type (optional)',
    'ai.generator.entityTypePlaceholder': 'e.g., User, Product, Order',
    'ai.generator.generating': 'Generating...',
    'ai.generator.generateForm': 'Generate Form',
    'ai.generator.generateTable': 'Generate Table',
    'ai.generator.preview': 'Preview',
    'ai.generator.noFormYet': 'Generated form will appear here',
    'ai.generator.noTableYet': 'Generated table will appear here',

    // Projects page
    'projects.title': 'Projects',
    'projects.description': 'Manage your projects and tasks',
    'projects.new': 'New Project',
    'projects.search': 'Search projects...',
    'projects.noProjects': 'No projects yet',
    'projects.noProjectsDesc': 'Create your first project to start organizing tasks',
    'projects.create': 'Create Project',
    'projects.createNew': 'Create New Project',
    'projects.archived': 'Archived',
    'projects.members': 'members',
    'projects.owner': 'Owner',
    'projects.previous': 'Previous',
    'projects.next': 'Next',
    'projects.pageOf': 'Page {page} of {total}',

    // Teams page
    'teams.title': 'Teams',
    'teams.description': 'Manage your teams and collaborations',
    'teams.new': 'New Team',
    'teams.createNew': 'Create New Team',
    'teams.name': 'Team Name',
    'teams.teamDescription': 'Description',
    'teams.descPlaceholder': 'Describe your team...',
    'teams.namePlaceholder': 'My Team',
    'teams.public': 'Public Team',
    'teams.publicDesc': 'Anyone can discover and join this team',
    'teams.cancel': 'Cancel',
    'teams.creating': 'Creating...',
    'teams.create': 'Create Team',
    'teams.search': 'Search teams...',
    'teams.noTeams': 'No teams yet',
    'teams.noTeamsDesc': 'Create a team to collaborate with others',
    'teams.publicBadge': 'Public',
    'teams.members': 'members',
    'teams.created': 'Team created',
    'teams.createdDesc': 'Your team has been successfully created.',
    'teams.error': 'Error',
    'teams.errorDesc': 'Failed to create team',

    // Dashboard page
    'dashboard.title': 'Dashboard',
    'dashboard.description': 'Overview of your work and progress',
    'dashboard.loading': 'Loading dashboard...',
    'dashboard.error': 'Something went wrong',
    'dashboard.admin.title': 'Admin Dashboard',
    'dashboard.admin.description': 'System-wide overview and statistics',
    'dashboard.totalUsers': 'Total Users',
    'dashboard.active': 'active',
    'dashboard.thisMonth': 'this month',
    'dashboard.projects': 'Projects',
    'dashboard.archived': 'archived',
    'dashboard.tasks': 'Tasks',
    'dashboard.completed': 'completed',
    'dashboard.overdue': 'Overdue',
    'dashboard.teams': 'Teams',
    'dashboard.activeTeams': 'Active teams',
    'dashboard.timeTrackedTotal': 'Time Tracked (Total)',
    'dashboard.allTime': 'All time',
    'dashboard.timeThisMonth': 'Time This Month',
    'dashboard.currentMonth': 'Current month',
    'dashboard.tasksCreated': 'Tasks Created',
    'dashboard.topProjects': 'Top Projects',
    'dashboard.noProjects': 'No projects yet',
    'dashboard.members': 'members',
    'dashboard.tasksLabel': 'tasks',
    'dashboard.topContributors': 'Top Contributors',
    'dashboard.noUserActivity': 'No user activity yet',
    'dashboard.totalTasks': 'Total Tasks',
    'dashboard.tasksPastDue': 'Tasks past due date',
    'dashboard.completionRate': 'completion rate',

    // Auth pages
    'auth.login': 'Login',
    'auth.register': 'Register',
    'auth.forgotPassword': 'Forgot Password',
    'auth.resetPassword': 'Reset Password',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.rememberMe': 'Remember me',
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.noAccount': 'Don\'t have an account?',
    'auth.haveAccount': 'Already have an account?',
    'auth.sendResetLink': 'Send Reset Link',
    'auth.backToLogin': 'Back to Login',

    // Pagination
    'pagination.previous': 'Previous',
    'pagination.next': 'Next',
    'pagination.page': 'Page',
    'pagination.of': 'of',
  },
  ru: {
    // Navigation
    'nav.dashboard': 'Главная',
    'nav.projects': 'Проекты',
    'nav.tasks': 'Мои задачи',
    'nav.teams': 'Команды',
    'nav.calendar': 'Календарь',
    'nav.time': 'Учёт времени',
    'nav.notifications': 'Уведомления',
    'nav.settings': 'Настройки',
    'nav.analytics': 'Аналитика',
    'nav.admin': 'Админ панель',
    'nav.logout': 'Выйти',

    // Admin Navigation
    'nav.admin.title': 'Администрирование',
    'nav.admin.users': 'Пользователи',
    'nav.admin.projects': 'Все проекты',
    'nav.admin.tasks': 'Все задачи',
    'nav.admin.handbooks': 'Справочники',
    'nav.admin.roles': 'Роли системы',
    'nav.admin.permissions': 'Права доступа',

    // Admin Page
    'admin.description': 'Администрирование и управление системой',
    'admin.users.desc': 'Управление аккаунтами и ролями пользователей',
    'admin.projects.desc': 'Просмотр и управление всеми проектами',
    'admin.tasks.desc': 'Просмотр и управление всеми задачами',
    'admin.handbooks.desc': 'Управление справочными данными системы',
    'admin.roles.desc': 'Управление системными ролями',
    'admin.permissions.desc': 'Настройка прав доступа к API',

    // Settings page
    'settings.title': 'Настройки',
    'settings.description': 'Управление настройками аккаунта и предпочтениями',
    'settings.profile': 'Профиль',
    'settings.notifications': 'Уведомления',
    'settings.appearance': 'Внешний вид',
    'settings.security': 'Безопасность',
    'settings.profileInfo': 'Информация профиля',
    'settings.profileDesc': 'Обновите вашу личную информацию',
    'settings.firstName': 'Имя',
    'settings.lastName': 'Фамилия',
    'settings.phone': 'Номер телефона',
    'settings.saveChanges': 'Сохранить изменения',
    'settings.notificationPrefs': 'Настройки уведомлений',
    'settings.notificationDesc': 'Выберите какие уведомления вы хотите получать',
    'settings.emailNotifications': 'Email уведомления',
    'settings.emailNotificationsDesc': 'Получать уведомления по электронной почте',
    'settings.notifyWhen': 'Уведомлять когда:',
    'settings.taskAssigned': 'Мне назначена задача',
    'settings.taskCommented': 'Кто-то комментирует мою задачу',
    'settings.taskCompleted': 'Отслеживаемая задача выполнена',
    'settings.deadlineReminder': 'Приближается срок задачи',
    'settings.appearanceTitle': 'Внешний вид',
    'settings.appearanceDesc': 'Настройте внешний вид TaskFlow',
    'settings.theme': 'Тема',
    'settings.themeLight': 'Светлая',
    'settings.themeDark': 'Тёмная',
    'settings.themeSystem': 'Системная',
    'settings.themeDesc': 'Выберите предпочитаемую тему',
    'settings.language': 'Язык',
    'settings.languageDesc': 'Выберите предпочитаемый язык',
    'settings.changePassword': 'Изменить пароль',
    'settings.changePasswordDesc': 'Обновите пароль для безопасности аккаунта',
    'settings.currentPassword': 'Текущий пароль',
    'settings.newPassword': 'Новый пароль',
    'settings.confirmPassword': 'Подтвердите новый пароль',

    // Telegram
    'settings.telegramNotifications': 'Telegram уведомления',
    'settings.telegramNotificationsDesc': 'Получать уведомления через Telegram',
    'settings.telegramConnected': 'Подключен',
    'settings.telegramNotConnected': 'Не подключен',
    'settings.telegramConnect': 'Подключить Telegram',
    'settings.telegramDisconnect': 'Отключить',
    'settings.telegramConnectTitle': 'Подключение Telegram',
    'settings.telegramConnectDesc': 'Отсканируйте QR-код или нажмите на ссылку для подключения Telegram',
    'settings.telegramCode': 'Ваш код',
    'settings.telegramOpenBot': 'Открыть Telegram бот',
    'settings.telegramConnectedAs': 'Подключен как',
    'settings.inAppNotifications': 'Уведомления в приложении',
    'settings.inAppNotificationsDesc': 'Показывать уведомления в приложении',
    'settings.notificationChannels': 'Каналы уведомлений',
    'settings.mentioned': 'Кто-то упоминает меня',
    'settings.projectInvite': 'Получено приглашение в проект',

    // Common
    'common.save': 'Сохранить',
    'common.cancel': 'Отмена',
    'common.delete': 'Удалить',
    'common.edit': 'Редактировать',
    'common.create': 'Создать',
    'common.search': 'Поиск',
    'common.loading': 'Загрузка...',
    'common.error': 'Ошибка',
    'common.success': 'Успешно',

    // Toast messages
    'toast.profileUpdated': 'Профиль обновлён',
    'toast.profileUpdatedDesc': 'Ваш профиль успешно обновлён.',
    'toast.profileError': 'Не удалось обновить профиль. Попробуйте ещё раз.',
    'toast.passwordChanged': 'Пароль изменён',
    'toast.passwordChangedDesc': 'Ваш пароль успешно изменён.',
    'toast.passwordError': 'Не удалось изменить пароль. Проверьте текущий пароль.',

    // Calendar
    'calendar.title': 'Календарь',
    'calendar.description': 'Просмотр задач и сроков',
    'calendar.today': 'Сегодня',
    'calendar.selectDate': 'Выберите дату',
    'calendar.noTasks': 'Нет задач на эту дату',
    'calendar.clickToView': 'Нажмите на дату для просмотра задач',
    'calendar.more': 'ещё',
    'calendar.sun': 'Вс',
    'calendar.mon': 'Пн',
    'calendar.tue': 'Вт',
    'calendar.wed': 'Ср',
    'calendar.thu': 'Чт',
    'calendar.fri': 'Пт',
    'calendar.sat': 'Сб',

    // Tasks
    'tasks.title': 'Мои задачи',
    'tasks.description': 'Просмотр и управление назначенными задачами',
    'tasks.search': 'Поиск задач...',
    'tasks.filterByStatus': 'Фильтр по статусу',
    'tasks.filterAll': 'Все задачи',
    'tasks.filterTodo': 'К выполнению',
    'tasks.filterInProgress': 'В работе',
    'tasks.filterDone': 'Выполнено',
    'tasks.filterOverdue': 'Просрочено',
    'tasks.noTasks': 'Задачи не найдены',
    'tasks.noTasksDesc': 'Назначенные вам задачи появятся здесь',
    'tasks.tryAdjustingFilters': 'Попробуйте изменить фильтры',
    'tasks.today': 'Сегодня',
    'tasks.comments': 'комментариев',

    // AI Generator
    'nav.admin.aiGenerator': 'AI Генератор',
    'admin.aiGenerator.desc': 'Генерация форм и таблиц с помощью AI',
    'ai.generator.title': 'AI Генератор',
    'ai.generator.description': 'Генерация форм и таблиц с помощью AI на основе описания на естественном языке',
    'ai.generator.formTab': 'Генератор форм',
    'ai.generator.tableTab': 'Генератор таблиц',
    'ai.generator.formInput': 'Описание формы',
    'ai.generator.formInputDesc': 'Опишите какую форму вы хотите сгенерировать',
    'ai.generator.tableInput': 'Описание таблицы',
    'ai.generator.tableInputDesc': 'Опишите какую таблицу вы хотите сгенерировать',
    'ai.generator.prompt': 'Описание',
    'ai.generator.formPromptPlaceholder': 'например, Создай форму регистрации пользователя с полями имя, email, пароль и телефон',
    'ai.generator.tablePromptPlaceholder': 'например, Создай таблицу для управления товарами с колонками название, цена, количество и категория',
    'ai.generator.entityType': 'Тип сущности (необязательно)',
    'ai.generator.entityTypePlaceholder': 'например, Пользователь, Товар, Заказ',
    'ai.generator.generating': 'Генерация...',
    'ai.generator.generateForm': 'Сгенерировать форму',
    'ai.generator.generateTable': 'Сгенерировать таблицу',
    'ai.generator.preview': 'Предпросмотр',
    'ai.generator.noFormYet': 'Сгенерированная форма появится здесь',
    'ai.generator.noTableYet': 'Сгенерированная таблица появится здесь',

    // Projects page
    'projects.title': 'Проекты',
    'projects.description': 'Управление проектами и задачами',
    'projects.new': 'Новый проект',
    'projects.search': 'Поиск проектов...',
    'projects.noProjects': 'Проектов пока нет',
    'projects.noProjectsDesc': 'Создайте первый проект для организации задач',
    'projects.create': 'Создать проект',
    'projects.createNew': 'Создать новый проект',
    'projects.archived': 'В архиве',
    'projects.members': 'участников',
    'projects.owner': 'Владелец',
    'projects.previous': 'Назад',
    'projects.next': 'Вперёд',
    'projects.pageOf': 'Страница {page} из {total}',

    // Teams page
    'teams.title': 'Команды',
    'teams.description': 'Управление командами и совместной работой',
    'teams.new': 'Новая команда',
    'teams.createNew': 'Создать новую команду',
    'teams.name': 'Название команды',
    'teams.teamDescription': 'Описание',
    'teams.descPlaceholder': 'Опишите вашу команду...',
    'teams.namePlaceholder': 'Моя команда',
    'teams.public': 'Публичная команда',
    'teams.publicDesc': 'Любой может найти и присоединиться к этой команде',
    'teams.cancel': 'Отмена',
    'teams.creating': 'Создание...',
    'teams.create': 'Создать команду',
    'teams.search': 'Поиск команд...',
    'teams.noTeams': 'Команд пока нет',
    'teams.noTeamsDesc': 'Создайте команду для совместной работы',
    'teams.publicBadge': 'Публичная',
    'teams.members': 'участников',
    'teams.created': 'Команда создана',
    'teams.createdDesc': 'Ваша команда успешно создана.',
    'teams.error': 'Ошибка',
    'teams.errorDesc': 'Не удалось создать команду',

    // Dashboard page
    'dashboard.title': 'Главная',
    'dashboard.description': 'Обзор вашей работы и прогресса',
    'dashboard.loading': 'Загрузка...',
    'dashboard.error': 'Что-то пошло не так',
    'dashboard.admin.title': 'Панель администратора',
    'dashboard.admin.description': 'Общая статистика системы',
    'dashboard.totalUsers': 'Всего пользователей',
    'dashboard.active': 'активных',
    'dashboard.thisMonth': 'в этом месяце',
    'dashboard.projects': 'Проекты',
    'dashboard.archived': 'в архиве',
    'dashboard.tasks': 'Задачи',
    'dashboard.completed': 'выполнено',
    'dashboard.overdue': 'Просрочено',
    'dashboard.teams': 'Команды',
    'dashboard.activeTeams': 'Активных команд',
    'dashboard.timeTrackedTotal': 'Учтено времени (всего)',
    'dashboard.allTime': 'За всё время',
    'dashboard.timeThisMonth': 'Время за месяц',
    'dashboard.currentMonth': 'Текущий месяц',
    'dashboard.tasksCreated': 'Создано задач',
    'dashboard.topProjects': 'Топ проектов',
    'dashboard.noProjects': 'Проектов пока нет',
    'dashboard.members': 'участников',
    'dashboard.tasksLabel': 'задач',
    'dashboard.topContributors': 'Топ участников',
    'dashboard.noUserActivity': 'Активности пока нет',
    'dashboard.totalTasks': 'Всего задач',
    'dashboard.tasksPastDue': 'Просроченных задач',
    'dashboard.completionRate': 'выполнено',

    // Auth pages
    'auth.login': 'Вход',
    'auth.register': 'Регистрация',
    'auth.forgotPassword': 'Забыли пароль',
    'auth.resetPassword': 'Сброс пароля',
    'auth.email': 'Email',
    'auth.password': 'Пароль',
    'auth.rememberMe': 'Запомнить меня',
    'auth.signIn': 'Войти',
    'auth.signUp': 'Зарегистрироваться',
    'auth.noAccount': 'Нет аккаунта?',
    'auth.haveAccount': 'Уже есть аккаунт?',
    'auth.sendResetLink': 'Отправить ссылку',
    'auth.backToLogin': 'Вернуться к входу',

    // Pagination
    'pagination.previous': 'Назад',
    'pagination.next': 'Вперёд',
    'pagination.page': 'Страница',
    'pagination.of': 'из',
  },
  ky: {
    // Navigation
    'nav.dashboard': 'Башкы бет',
    'nav.projects': 'Долбоорлор',
    'nav.tasks': 'Менин тапшырмаларым',
    'nav.teams': 'Командалар',
    'nav.calendar': 'Календарь',
    'nav.time': 'Убакыт эсеби',
    'nav.notifications': 'Билдирүүлөр',
    'nav.settings': 'Жөндөөлөр',
    'nav.analytics': 'Аналитика',
    'nav.admin': 'Админ панели',
    'nav.logout': 'Чыгуу',

    // Admin Navigation
    'nav.admin.title': 'Администрация',
    'nav.admin.users': 'Колдонуучулар',
    'nav.admin.projects': 'Бардык долбоорлор',
    'nav.admin.tasks': 'Бардык тапшырмалар',
    'nav.admin.handbooks': 'Маалымат китеби',
    'nav.admin.roles': 'Система ролдору',
    'nav.admin.permissions': 'Уруксаттар',

    // Admin Page
    'admin.description': 'Системаны администрациялоо жана башкаруу',
    'admin.users.desc': 'Колдонуучу аккаунттарын жана ролдорун башкаруу',
    'admin.projects.desc': 'Бардык долбоорлорду көрүү жана башкаруу',
    'admin.tasks.desc': 'Бардык тапшырмаларды көрүү жана башкаруу',
    'admin.handbooks.desc': 'Системанын маалымат китептерин башкаруу',
    'admin.roles.desc': 'Система ролдорун башкаруу',
    'admin.permissions.desc': 'API уруксаттарын тууралоо',

    // Settings page
    'settings.title': 'Жөндөөлөр',
    'settings.description': 'Аккаунт жөндөөлөрүн башкаруу',
    'settings.profile': 'Профиль',
    'settings.notifications': 'Билдирүүлөр',
    'settings.appearance': 'Көрүнүш',
    'settings.security': 'Коопсуздук',
    'settings.profileInfo': 'Профиль маалыматы',
    'settings.profileDesc': 'Жеке маалыматыңызды жаңыртыңыз',
    'settings.firstName': 'Аты',
    'settings.lastName': 'Фамилиясы',
    'settings.phone': 'Телефон номери',
    'settings.saveChanges': 'Өзгөртүүлөрдү сактоо',
    'settings.notificationPrefs': 'Билдирүү жөндөөлөрү',
    'settings.notificationDesc': 'Кайсы билдирүүлөрдү алууну тандаңыз',
    'settings.emailNotifications': 'Email билдирүүлөр',
    'settings.emailNotificationsDesc': 'Email аркылуу билдирүүлөрдү алуу',
    'settings.notifyWhen': 'Мени кабарлоо:',
    'settings.taskAssigned': 'Мага тапшырма берилгенде',
    'settings.taskCommented': 'Тапшырмама комментарий жазылганда',
    'settings.taskCompleted': 'Көзөмөлдөгөн тапшырма аткарылганда',
    'settings.deadlineReminder': 'Тапшырманын мөөнөтү жакындаганда',
    'settings.appearanceTitle': 'Көрүнүш',
    'settings.appearanceDesc': 'TaskFlow көрүнүшүн тууралаңыз',
    'settings.theme': 'Тема',
    'settings.themeLight': 'Жарык',
    'settings.themeDark': 'Караңгы',
    'settings.themeSystem': 'Системалык',
    'settings.themeDesc': 'Каалаган теманы тандаңыз',
    'settings.language': 'Тил',
    'settings.languageDesc': 'Каалаган тилди тандаңыз',
    'settings.changePassword': 'Сырсөздү өзгөртүү',
    'settings.changePasswordDesc': 'Коопсуздук үчүн сырсөздү жаңыртыңыз',
    'settings.currentPassword': 'Учурдагы сырсөз',
    'settings.newPassword': 'Жаңы сырсөз',
    'settings.confirmPassword': 'Жаңы сырсөздү ырастаңыз',

    // Telegram
    'settings.telegramNotifications': 'Telegram билдирүүлөр',
    'settings.telegramNotificationsDesc': 'Telegram аркылуу билдирүүлөрдү алуу',
    'settings.telegramConnected': 'Туташкан',
    'settings.telegramNotConnected': 'Туташкан эмес',
    'settings.telegramConnect': 'Telegram туташтыруу',
    'settings.telegramDisconnect': 'Ажыратуу',
    'settings.telegramConnectTitle': 'Telegram туташтыруу',
    'settings.telegramConnectDesc': 'QR-кодду сканерлеңиз же шилтемени басыңыз',
    'settings.telegramCode': 'Сиздин код',
    'settings.telegramOpenBot': 'Telegram ботту ачуу',
    'settings.telegramConnectedAs': 'Туташкан',
    'settings.inAppNotifications': 'Колдонмодогу билдирүүлөр',
    'settings.inAppNotificationsDesc': 'Колдонмодо билдирүүлөрдү көрсөтүү',
    'settings.notificationChannels': 'Билдирүү каналдары',
    'settings.mentioned': 'Мени кимдир бирөө айтканда',
    'settings.projectInvite': 'Долбоорго чакыруу алганда',

    // Common
    'common.save': 'Сактоо',
    'common.cancel': 'Жокко чыгаруу',
    'common.delete': 'Өчүрүү',
    'common.edit': 'Түзөтүү',
    'common.create': 'Түзүү',
    'common.search': 'Издөө',
    'common.loading': 'Жүктөлүүдө...',
    'common.error': 'Ката',
    'common.success': 'Ийгилик',

    // Toast messages
    'toast.profileUpdated': 'Профиль жаңыртылды',
    'toast.profileUpdatedDesc': 'Профилиңиз ийгиликтүү жаңыртылды.',
    'toast.profileError': 'Профилди жаңыртуу мүмкүн болбоду. Кайра аракет кылыңыз.',
    'toast.passwordChanged': 'Сырсөз өзгөртүлдү',
    'toast.passwordChangedDesc': 'Сырсөзүңүз ийгиликтүү өзгөртүлдү.',
    'toast.passwordError': 'Сырсөздү өзгөртүү мүмкүн болбоду. Учурдагы сырсөздү текшериңиз.',

    // Calendar
    'calendar.title': 'Календарь',
    'calendar.description': 'Тапшырмаларды жана мөөнөттөрдү көрүү',
    'calendar.today': 'Бүгүн',
    'calendar.selectDate': 'Датаны тандаңыз',
    'calendar.noTasks': 'Бул датада тапшырма жок',
    'calendar.clickToView': 'Тапшырмаларды көрүү үчүн датаны басыңыз',
    'calendar.more': 'дагы',
    'calendar.sun': 'Жек',
    'calendar.mon': 'Дүй',
    'calendar.tue': 'Шей',
    'calendar.wed': 'Шар',
    'calendar.thu': 'Бей',
    'calendar.fri': 'Жум',
    'calendar.sat': 'Ише',

    // Tasks
    'tasks.title': 'Менин тапшырмаларым',
    'tasks.description': 'Дайындалган тапшырмаларды көрүү жана башкаруу',
    'tasks.search': 'Тапшырмаларды издөө...',
    'tasks.filterByStatus': 'Статус боюнча чыпкалоо',
    'tasks.filterAll': 'Бардык тапшырмалар',
    'tasks.filterTodo': 'Аткарылуучу',
    'tasks.filterInProgress': 'Аткарылууда',
    'tasks.filterDone': 'Аткарылды',
    'tasks.filterOverdue': 'Мөөнөтү өткөн',
    'tasks.noTasks': 'Тапшырмалар табылган жок',
    'tasks.noTasksDesc': 'Сизге дайындалган тапшырмалар бул жерде көрүнөт',
    'tasks.tryAdjustingFilters': 'Чыпкаларды өзгөртүп көрүңүз',
    'tasks.today': 'Бүгүн',
    'tasks.comments': 'комментарий',

    // AI Generator
    'nav.admin.aiGenerator': 'AI Генератор',
    'admin.aiGenerator.desc': 'AI менен форма жана таблицаларды түзүү',
    'ai.generator.title': 'AI Генератор',
    'ai.generator.description': 'Табигый тилде жазылган сүрөттөмө боюнча AI менен форма жана таблицаларды түзүү',
    'ai.generator.formTab': 'Форма генератору',
    'ai.generator.tableTab': 'Таблица генератору',
    'ai.generator.formInput': 'Форманын сүрөттөмөсү',
    'ai.generator.formInputDesc': 'Кандай форма түзүүнү каалаарыңызды сүрөттөңүз',
    'ai.generator.tableInput': 'Таблицанын сүрөттөмөсү',
    'ai.generator.tableInputDesc': 'Кандай таблица түзүүнү каалаарыңызды сүрөттөңүз',
    'ai.generator.prompt': 'Сүрөттөмө',
    'ai.generator.formPromptPlaceholder': 'мисалы, Колдонуучуну каттоо формасын түзүңүз: аты, email, сырсөз жана телефон талаалары менен',
    'ai.generator.tablePromptPlaceholder': 'мисалы, Товарларды башкаруу үчүн таблица түзүңүз: аталышы, баасы, саны жана категориясы мамычалары менен',
    'ai.generator.entityType': 'Объект түрү (милдеттүү эмес)',
    'ai.generator.entityTypePlaceholder': 'мисалы, Колдонуучу, Товар, Заказ',
    'ai.generator.generating': 'Түзүлүүдө...',
    'ai.generator.generateForm': 'Форма түзүү',
    'ai.generator.generateTable': 'Таблица түзүү',
    'ai.generator.preview': 'Алдын ала көрүү',
    'ai.generator.noFormYet': 'Түзүлгөн форма бул жерде көрүнөт',
    'ai.generator.noTableYet': 'Түзүлгөн таблица бул жерде көрүнөт',

    // Projects page
    'projects.title': 'Долбоорлор',
    'projects.description': 'Долбоорлорду жана тапшырмаларды башкаруу',
    'projects.new': 'Жаңы долбоор',
    'projects.search': 'Долбоорлорду издөө...',
    'projects.noProjects': 'Долбоорлор жок',
    'projects.noProjectsDesc': 'Тапшырмаларды уюштуруу үчүн биринчи долбооруңузду түзүңүз',
    'projects.create': 'Долбоор түзүү',
    'projects.createNew': 'Жаңы долбоор түзүү',
    'projects.archived': 'Архивде',
    'projects.members': 'катышуучу',
    'projects.owner': 'Ээси',
    'projects.previous': 'Артка',
    'projects.next': 'Алдыга',
    'projects.pageOf': 'Барак {page} ичинен {total}',

    // Teams page
    'teams.title': 'Командалар',
    'teams.description': 'Командаларды жана кызматташууну башкаруу',
    'teams.new': 'Жаңы команда',
    'teams.createNew': 'Жаңы команда түзүү',
    'teams.name': 'Команданын аты',
    'teams.teamDescription': 'Сүрөттөмө',
    'teams.descPlaceholder': 'Командаңызды сүрөттөңүз...',
    'teams.namePlaceholder': 'Менин командам',
    'teams.public': 'Ачык команда',
    'teams.publicDesc': 'Ким болбосун таап, кошула алат',
    'teams.cancel': 'Жокко чыгаруу',
    'teams.creating': 'Түзүлүүдө...',
    'teams.create': 'Команда түзүү',
    'teams.search': 'Командаларды издөө...',
    'teams.noTeams': 'Командалар жок',
    'teams.noTeamsDesc': 'Кызматташуу үчүн команда түзүңүз',
    'teams.publicBadge': 'Ачык',
    'teams.members': 'катышуучу',
    'teams.created': 'Команда түзүлдү',
    'teams.createdDesc': 'Командаңыз ийгиликтүү түзүлдү.',
    'teams.error': 'Ката',
    'teams.errorDesc': 'Команда түзүү мүмкүн болгон жок',

    // Dashboard page
    'dashboard.title': 'Башкы бет',
    'dashboard.description': 'Иштин жана прогресстин обзору',
    'dashboard.loading': 'Жүктөлүүдө...',
    'dashboard.error': 'Бир нерсе туура эмес болду',
    'dashboard.admin.title': 'Админ панели',
    'dashboard.admin.description': 'Системанын жалпы статистикасы',
    'dashboard.totalUsers': 'Бардык колдонуучулар',
    'dashboard.active': 'активдүү',
    'dashboard.thisMonth': 'бул айда',
    'dashboard.projects': 'Долбоорлор',
    'dashboard.archived': 'архивде',
    'dashboard.tasks': 'Тапшырмалар',
    'dashboard.completed': 'аткарылды',
    'dashboard.overdue': 'Мөөнөтү өткөн',
    'dashboard.teams': 'Командалар',
    'dashboard.activeTeams': 'Активдүү командалар',
    'dashboard.timeTrackedTotal': 'Эсептелген убакыт (жалпы)',
    'dashboard.allTime': 'Бардык убакыт',
    'dashboard.timeThisMonth': 'Бул айдагы убакыт',
    'dashboard.currentMonth': 'Учурдагы ай',
    'dashboard.tasksCreated': 'Түзүлгөн тапшырмалар',
    'dashboard.topProjects': 'Мыкты долбоорлор',
    'dashboard.noProjects': 'Долбоорлор жок',
    'dashboard.members': 'катышуучу',
    'dashboard.tasksLabel': 'тапшырма',
    'dashboard.topContributors': 'Мыкты катышуучулар',
    'dashboard.noUserActivity': 'Активдүүлүк жок',
    'dashboard.totalTasks': 'Бардык тапшырмалар',
    'dashboard.tasksPastDue': 'Мөөнөтү өткөн тапшырмалар',
    'dashboard.completionRate': 'аткарылды',

    // Auth pages
    'auth.login': 'Кирүү',
    'auth.register': 'Каттоо',
    'auth.forgotPassword': 'Сырсөздү унуттуңузбу',
    'auth.resetPassword': 'Сырсөздү баштапкы абалга келтирүү',
    'auth.email': 'Email',
    'auth.password': 'Сырсөз',
    'auth.rememberMe': 'Мени эстеп кал',
    'auth.signIn': 'Кирүү',
    'auth.signUp': 'Катталуу',
    'auth.noAccount': 'Аккаунтуңуз жокпу?',
    'auth.haveAccount': 'Аккаунтуңуз барбы?',
    'auth.sendResetLink': 'Шилтеме жөнөтүү',
    'auth.backToLogin': 'Кирүүгө кайтуу',

    // Pagination
    'pagination.previous': 'Артка',
    'pagination.next': 'Алдыга',
    'pagination.page': 'Барак',
    'pagination.of': 'ичинен',
  },
};

const LanguageContext = React.createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = React.useState<Language>('ru');
  const [mounted, setMounted] = React.useState(false);

  React.useEffect(() => {
    const stored = localStorage.getItem('language') as Language | null;
    if (stored && ['en', 'ru', 'ky'].includes(stored)) {
      setLanguageState(stored);
    }
    setMounted(true);
  }, []);

  React.useEffect(() => {
    if (mounted) {
      document.documentElement.lang = language;
    }
  }, [language, mounted]);

  const setLanguage = React.useCallback((newLanguage: Language) => {
    setLanguageState(newLanguage);
    localStorage.setItem('language', newLanguage);
    document.documentElement.lang = newLanguage;
  }, []);

  const t = React.useCallback(
    (key: string): string => {
      return translations[language][key] || translations['en'][key] || key;
    },
    [language]
  );

  if (!mounted) {
    return <>{children}</>;
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = React.useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
